# Schema for the views plugins of the Audit Log DB module.

views.field.audit_log_db_message:
  type: views_field
  label: 'Log event message'
  mapping:
    replace_variables:
      type: boolean
      label: 'Replace variables'
